# Generated by Django 3.0 on 2026-02-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20260205_1014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Profile',
            table='profiles_profile',
        ),
    ]
