# Generated by Django 3.0 on 2026-02-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_address_letting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='lettings_address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='lettings_letting',
        ),
    ]
